### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by dev4pear**

### CODE REVIEW

**Comment by reinamora137** [comment]
1. Restore nearest neighbor on stamp page so images aren’t blurry

2. Make the fast forward arrows go to first or last stamp >> <<

3. Change the background color from pink to?? I like the original grey/black pattern but maybe something else is better? 

4. Perhaps default the stamp page to first stamp? 

5. Add estimated price to mint page after image upload. 

6. We need some better stamp related images or actual stamps we should link to in the top carousel. 

7. Fix filters on homepage so it shows src-721 vs src-20, etc.

8. change ‘news banner section’  to Posh Stamps

**Comment by dev4pear** [comment]
**1. Restore nearest neighbor on stamp page so images aren’t blurry**
I am not sure the meaning, let me fix this one at last.(Or it will be great if you can explain with screenshot or etc).

**2. Make the fast forward arrows go to first or last stamp >> <<**
Done

**3. Change the background color from pink to?? I like the original grey/black pattern but maybe something else is better?**
I think, this is related with designer. Or if you want original one, I can revert it into original grey/black pattern.

**4. Perhaps default the stamp page to first stamp?**
Done

**5. Add estimated price to mint page after image upload.**
I am currently not working here, so I will update you next week.

**6. We need some better stamp related images or actual stamps we should link to in the top carousel.**
I think, this one is also related with designer. Please keep me posted about this.

**7. Fix filters on homepage so it shows src-721 vs src-20, etc.**
Done

**8. change ‘news banner section’ to Posh Stamps**
Will do it soon.

**Comment by reinamora137** [comment]
> **1. Restore nearest neighbor on stamp page so images aren’t blurry** I am not sure the meaning, let me fix this one at last.(Or it will be great if you can explain with screenshot or etc).
> 
this is an example of how the images are now blurry. the original stamp page used a nearest neighbor css trick so they don't do this when scaled up. can pull from the stampchain.io site. 
image

something like
```

.pixelated {
    image-rendering: -moz-crisp-edges;
    image-rendering: -o-crisp-edges;
    image-rendering: -webkit-optimize-contrast;
    -ms-interpolation-mode: nearest-neighbor;
    image-rendering: pixelated;
}

```
> **2. Make the fast forward arrows go to first or last stamp >> <<** Done. -- update above
> 
> **3. Change the background color from pink to?? I like the original grey/black pattern but maybe something else is better?** I think, this is related with designer. Or if you want original one, I can revert it into original grey/black pattern. -- yes please revert to the original for now. 
> 
> **4. Perhaps default the stamp page to first stamp?** Done
> 
> **5. Add estimated price to mint page after image upload.** I am currently not working here, so I will update you next week.
> 
> **6. We need some better stamp related images or actual stamps we should link to in the top carousel.** I think, this one is also related with designer. Please keep me posted about this.
> 
> **7. Fix filters on homepage so it shows src-721 vs src-20, etc.** Done
> 
> **8. change ‘news banner section’ to Posh Stamps** Will do it soon. - done

**Comment by reinamora137** [comment]
new logo:

Stampchain 2 logo

**Comment by reinamora137** [comment]
merged into dev

**Pull request closed without merging**
